language: php
php:
    - 5.4
    - 5.5
    - 5.6

script:
    - vendor/bin/tester tests -s -p php -c tests/php.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
