language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
    - composer self-update

services: mongodb

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Mongo extension
    - pecl install -f mongo-1.3.0
    - composer install --no-interaction --dev --prefer-source
